version: "3.8"
services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Flow.Server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - grafana
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ASPNETCORE_ENVIRONMENT=Development

  collector:
    image: otel/opentelemetry-collector-contrib:0.81.0
    container_name: collector
    command: [ "--config=/etc/collector.yaml" ]
    ports:
      - "4317:4317" # Connection from app to grafana tempo
    volumes:
      - ./devops/otel/otel-collector-config.yml:/etc/collector.yaml
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./devops/tempo/tempo.yaml:/etc/tempo.yaml

  grafana:
    image: grafana/grafana:10.0.2
    container_name: grafana
    ports:
      - "3000:3000"  # Expose grafan Dashboard
    volumes:
      - ./devops/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - collector
      - tempo
